// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSKJ6JOCd626jCT24H3CL9F3zBb_zndkU',
    appId: '1:65862718917:web:5bb23061471b31d46ee7ac',
    messagingSenderId: '65862718917',
    projectId: 'usermanagement-abcad',
    authDomain: 'usermanagement-abcad.firebaseapp.com',
    storageBucket: 'usermanagement-abcad.appspot.com',
    measurementId: 'G-23DJ5YNDRZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ1nEGyv9I_ktszyInDSPMjqbEWoBlays',
    appId: '1:65862718917:android:ebdf7f5d7f1016386ee7ac',
    messagingSenderId: '65862718917',
    projectId: 'usermanagement-abcad',
    storageBucket: 'usermanagement-abcad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNqzQPfaQRvThb2ygMo6V29QxbONmfHJc',
    appId: '1:65862718917:ios:02bcaaf0ac551dad6ee7ac',
    messagingSenderId: '65862718917',
    projectId: 'usermanagement-abcad',
    storageBucket: 'usermanagement-abcad.appspot.com',
    iosBundleId: 'com.example.userManagementFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNqzQPfaQRvThb2ygMo6V29QxbONmfHJc',
    appId: '1:65862718917:ios:f60a5ecbb9a4be5a6ee7ac',
    messagingSenderId: '65862718917',
    projectId: 'usermanagement-abcad',
    storageBucket: 'usermanagement-abcad.appspot.com',
    iosBundleId: 'com.example.userManagementFirebase.RunnerTests',
  );
}
